### ISSUE TITLE
First improvements

### ISSUE THREAD

**Issue by skezh** [Taaldis/DragonImage#1]
1. Сделать так чтобы дракон поворачивался влево-вправо.
2. Сделать так чтобы он махал крыльями при нажатии на спейс.
3. нарисовать посередине земли замок - (можешь просто квадрат).
4. Сделать так чтобы пламя не проходило через землю. (Уменьшай высоту particle)
5. Нарисовать человечка с скажем луком (можно просто в пейнте маленькую фигурку)
6. Сделать так чтобы человечки ходили у замка и стояли на замке. (потом будет их жечь!)

**Comment by Taaldis** [comment]
Done
